export const cryptoCurrencies = [
  "Bitcoin (BTC)+ ⚡",
  "Litecoin (LTC)+ ⚡",
  "Ethereum (ETH)",
  "Bitcoin Cash (BCH)",
  "XRP (XRP)",
  "TRON (TRX)",
  "Dai (DAI)",
  "Ethereum Classic (ETC)",
  "Dogecoin (DOGE)",
  "iEx.ec (RLC)",
  "Stellar (XLM)",
  "Basic Attention Token (BAT)",
  "Aragon (ANT)",
  "Bancor Network Token (BNT)",
  "Civic (CVC)",
  "EOS (EOS)",
  "OMG Network (OMG)",
  "0x Protocol Token (ZRX)",
  "Qtum Ignition (QTUM)",
  "Storj (STORJ)",
  "DigiByte (DGB)",
  "Power Ledger (POWR)",
  "Binance Coin (BNB)",
  "Kyber Network (KNC)",
  "TrueUSD (TUSD)",
  "Chainlink (LINK)",
  "Tether (USDT)",
  "Bitcoin SV (BSV)",
  "VeChain (VET)",
  "Polkadot (DOT)",
  "Polygon (MATIC)",
  "USDC (USDC)",
  "Cardano (ADA)",
  "Uniswap (UNI)",
  "Binance USD (BUSD)",
  "Solana (SOL)",
  "Wrapped Bitcoin (WBTC)",
  "THETA (THETA)",
  "Internet Computer (ICP)",
  "Tezos (XTZ)",
  "Ravencoin (RVN)",
  "SushiSwap (SUSHI)",
  "Aave (AAVE)",
  "Algorand (ALGO)",
  "Enjin Coin (ENJ)",
  "Filecoin (FIL)",
  "Golem (GLM)",
  "The Graph (GRT)",
  "Loopring (LRC)",
  "Decentraland (MANA)",
  "Maker (MKR)",
  "Nexo (NEXO)",
  "PAX Gold (PAXG)",
  "Viberate (VIB)",
  "Waves (WAVES)",
  "NEM (XEM)",
  "yearn.finance (YFI)",
  "Chiliz (CHZ)",
  "Hedera Hashgraph (HBAR)",
  "Quant (QNT)",
  "Fantom (FTM)",
  "Holo (HOT)",
  "Huobi Token (HT)",
  "Zilliqa (ZIL)",
  "Compound (COMP)",
  "Ren (REN)",
  "SHIBA INU (SHIB)",
  "Kusama (KSM)",
];
